# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiddyer', '0002_authusergroups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthUserGroups',
            new_name='AuthUserGroup',
        ),
    ]
