# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiddyer', '0007_authuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('group_id', models.IntegerField()),
                ('create_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
