# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-19 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiddyer', '0008_appusergroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('create_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('icon', models.CharField(max_length=4096)),
                ('mobile_num', models.CharField(max_length=20)),
                ('create_Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
