# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-27 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiddyer', '0009_appgroup_appuserprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('location', models.CharField(max_length=1024)),
                ('coordinates', models.CharField(max_length=255)),
                ('create_Date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
