# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-28 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kiddyer', '0010_apptrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='apptrack',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
