# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-03 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiddyer', '0011_apptrack_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apptrack',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='appuserprofile',
            name='create_Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
